version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=account_service
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  account-statement-service:
    image: account-statement-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      dbUrl: jdbc:postgresql://localhost:5432/account_service
      dbUsername: root
      dbPassword: secret
      hdfcUsername : <user_name>
      jobCompanyName : <job_name>
      autoImportSecret : <import_secret>
      autoImportUrl : <import_url>
      autoImportToken : <import_token>
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data:
